trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md

variables:
  - template: variables.yml

resources:
  repositories:
    - repository: templates
      type: github
      name: decentralized-cloud/templates
      endpoint: decentralized-cloud

stages:
  - stage: Build_Test_Publish
    jobs:
      - template: build/build-test-publish.yml@templates
        parameters:
          vmImage: ${{variables.linuxVmImage}}
          gitVersion: ${{ variables.gitVersion }}
          gitVersionConfigFilePath: ${{ variables.gitVersionConfigFilePath }}
          grpcContractScriptFilePath: ${{ variables.grpcContractScriptFilePath }}
          grpcContractScriptworkingDirectory: ${{ variables.grpcContractScriptworkingDirectory }}
          dockerContainerRegistry: ${{variables.dockerContainerRegistry}}
          dockerRepositoryName: ${{variables.dockerRepositoryName}}
          dockerBuildFilePath: "$(system.defaultWorkingDirectory)/docker/Dockerfile.build"
          dockerBuildContext: "$(system.defaultWorkingDirectory)"
          dockerVersion: ${{variables.artifactVersion}}
          testDockerComposeFilePath: ${{ variables.testDockerComposeFilePath }}
          ciService: ${{ variables.ciService }}
          coverallsToken: ${{ variables.coverallsToken }}
          helmVersion: ${{ variables.helmVersion }}
          helmChartsDirectoryPath: ${{ variables.helmChartsDirectoryPath }}
          helmChartsOutputDirectoryPath: ${{ variables.helmChartsOutputDirectoryPath }}
          helmArtifactName: ${{ variables.helmArtifactName }}
