FROM microbusiness/protobuf-builder:latest
LABEL maintainer="morteza.alizadeh@gmail.com"

ADD ./contract/grpc /src
WORKDIR /src/proto
RUN mkdir -p ../go
RUN protoc \
    --go_opt=Mcommons.proto=./ \
    --go_opt=Muser-messages.proto=./ \
    --go_opt=Moperations.proto=./ \
    *.proto \
    --go_out=plugins=grpc:../go
