version: "3.7"
services:
  mongodb:
    image: mongo:4
    ports:
      - 27017
    networks:
      - the_net

  tests:
    build:
      context: ../
      dockerfile: docker/Dockerfile.testAndCoverage
    depends_on:
      - mongodb
    networks:
      - the_net

networks:
  the_net:
