FROM microbusiness/protobuf-builder:latest
LABEL maintainer="morteza.alizadeh@gmail.com"

ADD . /src
WORKDIR /src/contract/grpc/proto
RUN protoc --go_opt=Muser.proto=/src/contract/grpc/proto user.proto --go_out=plugins=grpc:../go
